# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('coordinates', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=30)),
                ('work_hours_begin', models.TimeField()),
                ('work_hours_end', models.TimeField()),
                ('force_close', models.BooleanField(default=False)),
                ('work_days_begin', models.CharField(choices=[('monday', '\u0535\u0580\u056f\u0578\u0582\u0577\u0561\u0562\u0569\u056b'), ('tuesday', '\u0535\u0580\u0565\u0584\u0577\u0561\u0562\u0569\u056b'), ('thursday', '\u0549\u0578\u0580\u0565\u0584\u0577\u0561\u0562\u0569\u056b'), ('wednesday', '\u0540\u056b\u0576\u0563\u0577\u0561\u0562\u0569\u056b'), ('thursday', '\u0548\u0582\u0580\u0562\u0561\u0569'), ('saturday', '\u0547\u0561\u0562\u0561\u0569'), ('sunday', '\u053f\u056b\u0580\u0561\u056f\u056b')], max_length=20)),
                ('work_days_end', models.CharField(choices=[('monday', '\u0535\u0580\u056f\u0578\u0582\u0577\u0561\u0562\u0569\u056b'), ('tuesday', '\u0535\u0580\u0565\u0584\u0577\u0561\u0562\u0569\u056b'), ('thursday', '\u0549\u0578\u0580\u0565\u0584\u0577\u0561\u0562\u0569\u056b'), ('wednesday', '\u0540\u056b\u0576\u0563\u0577\u0561\u0562\u0569\u056b'), ('thursday', '\u0548\u0582\u0580\u0562\u0561\u0569'), ('saturday', '\u0547\u0561\u0562\u0561\u0569'), ('sunday', '\u053f\u056b\u0580\u0561\u056f\u056b')], max_length=20)),
                ('main_pic', models.ImageField(upload_to='places/')),
                ('logo', models.ImageField(upload_to='places/')),
                ('description', models.TextField(max_length=1000)),
                ('slug', models.SlugField(unique=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type_title', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.ManyToManyField(to='places.PlaceType'),
        ),
        migrations.AddField(
            model_name='place',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
